fastlane_version "2.146.1"
default_platform :android

platform :android do
      lane :publish_to_firebase do |options|
       puts "build #"
               puts options[:build_num]
               puts ENV['APK_FILE_PATH']

       build_notes = "Environment: android. Branch: #{options[:branch]}. Notes: #{options[:notes]}. Built by #{options[:author]}"
           firebase_app_distribution(
                        app: "1:412851804939:android:64b228273d89418421e00e",
                        testers: "dilip.developer1987@gmail.com",
                        release_notes: "whole application design has been ready for this Vertical App",
                        apk_path: apk_paths,
                        firebase_cli_token:"1//0gkmN0CH8ozsxCgYIARAAGBASNwF-L9Irfmn_DmJeefTvTW5nMfjenkmmAzxjS_42a8xSGuVNmuDFvKukimz4aYmxW4rjCFaAkGA",
                        firebase_cli_path: "/usr/local/bin/firebase"
                    )

            end
end


