name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: build with gradle
        run: bash ./gradlew build
      - name: build debug apk
        run: bash ./gradlew assembleDebug

      - uses: r0adkll/sign-android-release@v1
        with:
         releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.SIGNING_KEY }}
         alias: ${{ secrets.ALIAS }}
         keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
         keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Build
        run: bash ./gradlew clean build

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'publish_to_firebase --env GoogleCustomSearch'