name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      # Ensure .gradle/caches is empty before writing to it.
      # This helps us stay within Github's cache size limits.
      - name: Clean Cache
        run: rm -rf ~/.gradle/caches

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Build
        run: bash ./gradlew clean build

                - name: Fastlane Action
                  uses: maierj/fastlane-action@v1.4.0
                  with:
                    lane: 'publish_to_firebase'