name: Testing Workflow


on:
  push:
    branches:
      - master
    jobs:
      build-android:
        strategy:
          matrix:
            platform: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
    steps:
      - uses: r0adkll/sign-android-release@v1
        with:
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          releaseDirectory: app/build/outputs/apk/release



