name: Testing Workflow


on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build release
        run:  bash ./gradlew assembleRelease
      - name: Deploy app distribution
        run: bash ./gradlew appDistributionUploadRelease


