name: firebase app distribution
on:
  push:
    branches:
      - master
    before_install:
      - gem install bundler
      - bundle --version
      - bundle install

    before_script:
      - curl -sL firebase.tools | bash

    android:
      components:
        # Uncomment the lines below if you want to
        # use the latest revision of Android SDK Tools
        # - tools
        # - platform-tools

        # The BuildTools version used by your project
        - build-tools-28.0.3

        # The SDK version used to compile your project
        - android-28

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-x86-android-26
        - sys-img-armeabi-v7a-android-17

    script:
      - bundle exec fastlane "publish_to_firebase"


  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # Ensure .gradle/caches is empty before writing to it.
      # This helps us stay within Github's cache size limits.
      - name: Clean Cache
        run: rm -rf ~/.gradle/caches

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Build
        run: bash ./gradlew clean build


      - uses: maierj/fastlane-action@v1.4.0
        with:
            lane: 'publish_to_firebase'