name: Testing Workflow

on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build release
        run:  bash ./gradlew assembleDebug --status

      - name: Upload artifact to Firebase Distribution
          uses: ./
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/release/app-release.apk
