name: Testing Workflow

on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build release
        run:  bash ./gradlew assembleDebug --status
  - name: Install Firebase
      run: yarn install
      - name: Upload APK
        run: yarn run firebase appdistribution:distribute build/app/outputs/apk/release/app-debug.apk --app "${{ secrets.ANDROID_APP_ID }}" --groups GROUP --token "${{ secrets.FIREBASE_TOKEN }}"
