name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: Build
      run: bash ./gradlew build

    - name: Assemble Release Bundle
      run: bash ./gradlew bundleRelease

    - name: sign release
    - uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
