name: Testing Workflow
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build for Android
        run: cd android && ./gradlew assembleRelease
      - name: Deploy to App Center
        uses: zackify/AppCenter-Github-Action@1.0.0
        with:
          appName: org/appname
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: group name
          file: android/app/build/outputs/apk/release/app-release.apk
