name: Testing Workflow


on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build release
        run:  bash ./gradlew assembleRelease --status

      - name: Deploy app distribution
        run: bash ./gradlew appDistributionUploadRelease


