name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - name: build release
        run:  bash ./gradlew assembleRelease --stacktrace

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'publish_to_firebase --env GoogleCustomSearch'