name: firebase app distribution
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build release
        run:  bash ./gradlew assembleRelease

      - name: Deploy app distribution
        run: bash ./gradlew appDistributionUploadRelease

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'publish_to_firebase'