name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - run: npm test
      - uses: ./
        with:
          milliseconds: 1000