name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
          # Step to Configure the JDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: bash ./gradlew clean build
       # Step to Build the Project and generate the APK
      - name: Build Debug
        run: bash ./gradlew assembleDebug

          # Restore the cache.
          # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'publish_to_firebase --env GoogleCustomSearch'

