name: firebase app distribution
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  build-android:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        # Step to install the NDK
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
        # Step to Build the Project and generate the APK
      - name: build debug apk
        run: bash ./gradlew assembleDebug

